/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guessgame;

import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author 6010
 */

interface CExam{ // interface class
        abstract int getWin();
        abstract int getLose();
        abstract int getCorrectNumber();
        abstract int setNumber();
       
}

public class gui extends javax.swing.JFrame implements CExam {

   
    /**
     * Creates new form gui
     */
   
    
    String br = System.getProperty("line.separator"); // new line 
    int answer;
    String input;
    Random ranNum = new Random(); // random number
    int w =0,l= 0;
    int count = 0;
    
    public gui() {
        
     answer = setNumber();
        initComponents(); 
        
        newgame.setEnabled(false);
        welcome(); // show welcome screen
        showwin(); //  show win number
        showlost(); // show lost number
    }
          
    public int getWin()
        { 
         w++; // count win
      
  
         return w;   
        }
     public int getLose()
     { 
            l++; // count lose
    
         return l;  
     }
     
     public int getCorrectNumber()
     {   //Get the correct number from this object.*  
         //@return int, Secret correct number.
         return answer;
     }
     public int setNumber() 
     {//Set random number. It should call when need new random number
        return 10 + ranNum.nextInt(99); 
     }
     
     public void showCorrect() // show message if it's correct
     {
         String showcor = "Well done, correct number is ;" +answer;
          display.setText(showcor);
          display.setForeground(Color.BLUE);
     }
     
     public void showhigher() // show message if it's higher
     {
         String showwrong = "It's greater than : " +input +br +br+
                            " try again !!";
          display.setText(showwrong);
          display.setForeground(Color.RED);
     }
     
     public void showlower() // show message if it's lower
     {
         String showwrong = "It's lower than : " +input +br +br+
                            " try again !!";
          display.setText(showwrong);
          display.setForeground(Color.RED);
     }
     
     
      public void showwin() // show win number
             {
                String win;
            win = String.valueOf(getWin());
                
          showWin.setText(win);
          showWin.setForeground(Color.BLUE);
             }
     public void showlost()// show lost number
     {
          String lost;
            lost = String.valueOf(getWin());
                
          showLost.setText(lost);
          showLost.setForeground(Color.RED);
            
     }
      public void welcome() // show message welcome
     {
         String welcome = "Welcome to guess game." +br+
                             "Start guessing number";
          display.setText(welcome);
          display.setForeground(Color.PINK);
     }
     
     public void startGame(String input)  // main game
     {
         
         int _input = Integer.parseInt(input);
         
         if(_input == answer)
         {
             showCorrect();
             getWin(); //if win
             //w++;
         }
         else if(_input>answer)
         {
             showlower(); // if lower
             getLose();
         }
         else if(_input<answer)
         {
             showhigher();
             getLose(); // if higher
         }
         
         if(count >= 4 && _input != answer)
         {
             String showwrong = "You lost !!"; // can play 5 times
          display.setText(showwrong);
          display.setForeground(Color.RED);
          guess.setEnabled(false);
          
         }
         count++; // count 5 time ++
         }
    
            
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        show = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        guess = new javax.swing.JButton();
        newgame = new javax.swing.JButton();
        showWin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        showLost = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        show.setText("Player Information W:");

        display.setColumns(20);
        display.setRows(5);
        jScrollPane1.setViewportView(display);

        guess.setText("Guess");
        guess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessActionPerformed(evt);
            }
        });

        newgame.setText("new game");
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });

        showWin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showWinActionPerformed(evt);
            }
        });

        jLabel1.setText("L:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(guess, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(newgame, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(show)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showWin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(showLost, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(show)
                    .addComponent(showWin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(showLost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guess, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newgame, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessActionPerformed
        // TODO add your handling code here:
        input = JOptionPane.showInputDialog("Please enter your number: ");
        startGame(input); // user input
    }//GEN-LAST:event_guessActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgameActionPerformed

    private void showWinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showWinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showWinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea display;
    private javax.swing.JButton guess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton newgame;
    private javax.swing.JLabel show;
    private javax.swing.JTextField showLost;
    private javax.swing.JTextField showWin;
    // End of variables declaration//GEN-END:variables
}
